In [1]:
!python -m pip install numpy

   ---------------------------------------- 0.0/12.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.8 MB ? eta -:--:--
    --------------------------------------- 0.3/12.8 MB ? eta -:--:--
    --------------------------------------- 0.3/12.8 MB ? eta -:--:--
    --------------------------------------- 0.3/12.8 MB ? eta -:--:--
   - -------------------------------------- 0.5/12.8 MB 386.5 kB/s eta 0:00:32
   - -------------------------------------- 0.5/12.8 MB 386.5 kB/s eta 0:00:32
   -- ------------------------------------- 0.8/12.8 MB 451.7 kB/s eta 0:00:27
   --- ------------------------------------ 1.0/12.8 MB 572.1 kB/s eta 0:00:21
   ---- ----------------------------------- 1.3/12.8 MB 662.4 kB/s eta 0:00:18
   ---- ----------------------------------- 1.3/12.8 MB 662.4 kB/s eta 0:00:18
   ----- ---------------------------------- 1.8/12.8 MB 774.2 kB/s eta 0:00:15
   ------ -----------------

  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

[notice] A new release of pip is available: 25.0.1 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
!python --upgrade pip



unknown option --upgrade
usage: python [option] ... [-c cmd | -m mod | file | -] [arg] ...
Try `python -h' for more information.


In [6]:
!python -h


usage: python [option] ... [-c cmd | -m mod | file | -] [arg] ...
Options (and corresponding environment variables):
-b     : issue warnings about converting bytes/bytearray to str and comparing
         bytes/bytearray with str or bytes with int. (-bb: issue errors)
-B     : don't write .pyc files on import; also PYTHONDONTWRITEBYTECODE=x
-c cmd : program passed in as string (terminates option list)
-d     : turn on parser debugging output (for experts only, only works on
         debug builds); also PYTHONDEBUG=x
-E     : ignore PYTHON* environment variables (such as PYTHONPATH)
-h     : print this help message and exit (also -? or --help)
-i     : inspect interactively after running script; forces a prompt even
         if stdin does not appear to be a terminal; also PYTHONINSPECT=x
-I     : isolate Python from the user's environment (implies -E and -s)
-m mod : run library module as a script (terminates option list)
-O     : remove assert and __debug__-dependent statements; add .op

In [37]:
!python -m pip install numpy


[notice] A new release of pip is available: 25.0.1 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip


In [38]:
!run: python.exe -m pip install --upgrade pip

'run:' is not recognized as an internal or external command,
operable program or batch file.


In [ ]:
#ndarray

In [8]:
import numpy as np
n=np.array([1,2,3,4])
print(n)
print(type(n))

[1 2 3 4]
<class 'numpy.ndarray'>


In [9]:
n2=np.array([[1,2,3],[5,6,4]])
print(n2)


[[1 2 3]
 [5 6 4]]


In [18]:
dim=2
shape=(2,3)
size=6

print(n.ndim,n2.ndim)
print(n.shape,n2.shape)
print(n.size,n2.size)

1 2
(4,) (2, 3)
4 6


In [ ]:
import numpy as np
a=np.array([1,2,4,5])
z=np.zeros((2,3))           #shape is a  mostly tuple 
print(z)



[[0. 0. 0.]
 [0. 0. 0.]]


In [3]:
import numpy as np
a=np.array([1,2,4,5])
z=np.zeros([2,3])
print(z)



[[0. 0. 0.]
 [0. 0. 0.]]


In [6]:
import numpy as np
a=np.array([1,2,4,5])
z=np.ones((2,3))
print(z)




[[1. 1. 1.]
 [1. 1. 1.]]


In [8]:
ones=np.ones((5,5))
print(ones)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [9]:
np.eye(5)


array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [16]:
np.random.random((3,3))

array([[0.44943497, 0.91415094, 0.05558143],
       [0.35799153, 0.43764812, 0.66084204],
       [0.88635228, 0.9553543 , 0.08935331]])

In [11]:
np.random.random((5))

array([0.65851914, 0.01916092, 0.1598019 , 0.43921749, 0.80480524])

In [18]:
np.random.random(1,11,(55))

TypeError: random() takes at most 1 positional argument (3 given)

In [24]:
#maths

a=np.array([1,2,3])
b=np.array([2,5,10])
c=a+b
print(c)
d=a-b
c=a*b
d=a**b
print(d)

[ 3  7 13]
[    1    32 59049]


In [21]:
c=a*b
print(c)

[ 2 10 30]


In [22]:
d=a-b
print(d)

[-1 -3 -7]


In [25]:
print(np.sin(a))
print(np.cos(a))
print(np.tan(b))

[0.84147098 0.90929743 0.14112001]
[ 0.54030231 -0.41614684 -0.9899925 ]
[-2.18503986 -3.38051501  0.64836083]


In [28]:
#maths &stast

x=np.array([[2,4]
           [5,11]])
print(x.mean())
print(x.mean(axis=0))

<>:3: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
<>:3: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
C:\Users\HP\AppData\Local\Temp\ipykernel_17220\2166997946.py:3: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
  x=np.array([[2,4]


TypeError: list indices must be integers or slices, not tuple

In [32]:
#maths &stast

x=np.array([[2,4]
           [5,11],
           [3,4]])
print(x.mean())

<>:3: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
<>:3: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
C:\Users\HP\AppData\Local\Temp\ipykernel_17220\3106618430.py:3: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
  x=np.array([[2,4]


TypeError: list indices must be integers or slices, not tuple

In [33]:
x=np.array([[2,4][5,11],[3,4]])
print(x.mean())

<>:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
<>:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
C:\Users\HP\AppData\Local\Temp\ipykernel_17220\4195610876.py:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
  x=np.array([[2,4][5,11],[3,4]])


TypeError: list indices must be integers or slices, not tuple

In [34]:
print(x.mean(axis=1))

NameError: name 'x' is not defined